from aenum import Enum


class EventType(Enum):
    RESOURCE_COUNT = "RESOURCE COUNT"
    USER_WAIT = "USER WAIT"
    RESOURCE_USAGE = "RESOURCE USAGE"
    SYSTEM_UTILIZATION = "SYSTEM UTILIZATION"
    USER_LOGIN = "USER LOGIN"
    SLA_BROKE = "SLA BROKEN"
